/*
 * File: TransActionForm.java
 * Created: 5/16/2020
 * 
 */
package bankregister;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.Scanner;

/**
 *
 * @author Eduardo Estrada
 */
public class TransActionForm extends javax.swing.JFrame {

    private BankAccount bankAccount;
    private ErrorMessages error;
    private String[] categories;

    /**
     * Creates new form TransActionForm
     */
    public TransActionForm() {
        error = new ErrorMessages();
        try {
            readCategoriesFile();
            initComponents();
            readAccountFile();
        } catch (FileNotFoundException ex) {
            error.errorMessage("File not found error: " + ex.getMessage());
            System.out.println(ex.getMessage());
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        }
       
    }// end constructor
    
    private void readCategoriesFile() throws FileNotFoundException, IOException{
        FileReader fileReader = new FileReader("categories.txt");
        BufferedReader bufferedReader = new BufferedReader(fileReader);
        ArrayList<String> lines = new ArrayList<>();
        String line = null;
        while ((line = bufferedReader.readLine()) != null) {
            lines.add(line);
        }
        bufferedReader.close();
       	categories =  lines.toArray(new String[lines.size()]);
       
    }// end readCategoriesFile

    private void readAccountFile() throws FileNotFoundException {

        File accountFile = new File("accountInfo.txt");
        String[] split_data;
        try (Scanner fileScanner = new Scanner(accountFile)) {
            String accountline;
            split_data = null;
            // loop thru the file
            while (fileScanner.hasNextLine()) {
                accountline = fileScanner.nextLine();
                split_data = accountline.split(",");
                
            }// end while
            // debug
            System.out.println(Arrays.toString(split_data));
        }
        String accountOwner = split_data[0].trim();
        String accountType = split_data[1].trim();
        float accountBala = Float.parseFloat(split_data[2].trim());

        bankAccount = new BankAccount(accountOwner, accountType, accountBala);
        balanceResultTxtFld.setText("$" + Float.toString(bankAccount.getBalance()));
        acctNameValueLbl.setText(bankAccount.getActype());

    }// end readAccountFile

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        transTypeBtnGroup = new javax.swing.ButtonGroup();
        titleLbl = new javax.swing.JLabel();
        dateLbl = new javax.swing.JLabel();
        categoryLbl = new javax.swing.JLabel();
        amntLbl = new javax.swing.JLabel();
        amtTxtFld = new javax.swing.JTextField();
        debitRdoBtn = new javax.swing.JRadioButton();
        depRdoBtn = new javax.swing.JRadioButton();
        addTransBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        balanceLbl = new javax.swing.JLabel();
        balanceResultTxtFld = new javax.swing.JTextField();
        acctNameLbl = new javax.swing.JLabel();
        acctNameValueLbl = new javax.swing.JLabel();
        payeeLbl = new javax.swing.JLabel();
        payeeTxtFld = new javax.swing.JTextField();
        checkNumLbl = new javax.swing.JLabel();
        checkNumTxtFld = new javax.swing.JTextField();
        datePicker = new org.jdesktop.swingx.JXDatePicker();
        categorComboBox = new javax.swing.JComboBox<>(categories);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        titleLbl.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        titleLbl.setText("Account Transaction Form");

        dateLbl.setText("Date:");

        categoryLbl.setText("Category:");

        amntLbl.setText("Amount:");

        amtTxtFld.setText(" ");
        amtTxtFld.setToolTipText("Transaction Amount $");

        transTypeBtnGroup.add(debitRdoBtn);
        debitRdoBtn.setText("(-)Debit");

        transTypeBtnGroup.add(depRdoBtn);
        depRdoBtn.setText("(+)Deposit");

        addTransBtn.setText("Enter");
        addTransBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTransBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("Exit");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        balanceLbl.setText("Balance:");

        balanceResultTxtFld.setEditable(false);
        balanceResultTxtFld.setText(" ");

        acctNameLbl.setText("Account Name:");

        acctNameValueLbl.setText("acct name");

        payeeLbl.setText("Payee:");

        payeeTxtFld.setText(" ");

        checkNumLbl.setText("Check #:");

        checkNumTxtFld.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(categoryLbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(debitRdoBtn)
                        .addGap(20, 20, 20)
                        .addComponent(depRdoBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(addTransBtn)
                        .addGap(6, 6, 6)
                        .addComponent(cancelBtn))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(84, 84, 84)
                            .addComponent(amntLbl)
                            .addGap(18, 18, 18)
                            .addComponent(amtTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(balanceLbl)
                                .addGap(18, 18, 18)
                                .addComponent(balanceResultTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(83, 83, 83)
                                    .addComponent(checkNumLbl)
                                    .addGap(18, 18, 18)
                                    .addComponent(checkNumTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(90, 90, 90)
                                        .addComponent(payeeLbl)
                                        .addGap(27, 27, 27)
                                        .addComponent(payeeTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(156, 156, 156)
                                        .addComponent(categorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(acctNameLbl)
                        .addGap(12, 12, 12)
                        .addComponent(acctNameValueLbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(dateLbl)
                        .addGap(18, 18, 18)
                        .addComponent(datePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(titleLbl)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(debitRdoBtn)
                    .addComponent(depRdoBtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(acctNameLbl)
                    .addComponent(acctNameValueLbl))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateLbl)
                    .addComponent(datePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(checkNumLbl))
                    .addComponent(checkNumTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(payeeLbl))
                    .addComponent(payeeTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoryLbl)
                    .addComponent(categorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(amntLbl))
                    .addComponent(amtTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(balanceLbl))
                    .addComponent(balanceResultTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addTransBtn)
                    .addComponent(cancelBtn))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void addTransBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTransBtnActionPerformed

        String datePattern = "dd/MM/yyyy";
        DateFormat dateFormat = new SimpleDateFormat(datePattern);
        float transAmount;
        
        try {
            Date selectedDate = datePicker.getDate();
            String transDate = dateFormat.format(selectedDate);
            transAmount = Float.parseFloat(amtTxtFld.getText());

            if (debitRdoBtn.isSelected()) {

                if (bankAccount.withdraw(transAmount, transDate, String.valueOf(categorComboBox.getSelectedItem()), payeeTxtFld.getText(), checkNumTxtFld.getText())) {
                    // clear fields
                    amtTxtFld.setText("");
                    
                    // dateTxtFld.setText("");
                    payeeTxtFld.setText("");
                    checkNumTxtFld.setText("");
                    balanceResultTxtFld.setText("$" + bankAccount.getBalanceAsString() );
                } else {
                    // display an error
                    System.out.println("withdrawal error");
                }

                System.out.println("add button pressed - withdrawal radio button is selected");

            } else if (depRdoBtn.isSelected()) {

                if (bankAccount.deposit(transAmount, transDate, String.valueOf(categorComboBox.getSelectedItem()), payeeTxtFld.getText(), checkNumTxtFld.getText())) {
                    // clear the fields
                    amtTxtFld.setText("");
                   
                    // dateTxtFld.setText("");
                    payeeTxtFld.setText("");
                    checkNumTxtFld.setText("");
                    balanceResultTxtFld.setText("$" + bankAccount.getBalanceAsString() );
                } else {
                    // display an error
                    System.out.println("deposit error");
                } // end if successful deposit
                
            } else {
                error.errorMessage("Select (-)debit or (+)deposit!");
            }// end if either radio button selected
            
        } catch (NumberFormatException numberFormatException) {
            error.errorMessage("Amount Field cannot be blank!");
            System.out.println(numberFormatException.getMessage());
        } catch (NullPointerException nullException){
            error.errorMessage("Date Field cannot be blank!");
            System.out.println(nullException.getMessage());
        
        }
    }//GEN-LAST:event_addTransBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        try {
            bankAccount.recordTransActions();
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        }
        dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            bankAccount.recordTransActions();
            dispose();
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_formWindowClosing
    /**
     * Starts a new runnable transaction form.
     */
    public static void displayForm() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransActionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransActionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransActionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransActionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TransActionForm().setVisible(true);
        });
    }// end displayForm()

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel acctNameLbl;
    private javax.swing.JLabel acctNameValueLbl;
    private javax.swing.JButton addTransBtn;
    private javax.swing.JLabel amntLbl;
    private javax.swing.JTextField amtTxtFld;
    private javax.swing.JLabel balanceLbl;
    private javax.swing.JTextField balanceResultTxtFld;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JComboBox<String> categorComboBox;
    private javax.swing.JLabel categoryLbl;
    private javax.swing.JLabel checkNumLbl;
    private javax.swing.JTextField checkNumTxtFld;
    private javax.swing.JLabel dateLbl;
    private org.jdesktop.swingx.JXDatePicker datePicker;
    private javax.swing.JRadioButton debitRdoBtn;
    private javax.swing.JRadioButton depRdoBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel payeeLbl;
    private javax.swing.JTextField payeeTxtFld;
    private javax.swing.JLabel titleLbl;
    private javax.swing.ButtonGroup transTypeBtnGroup;
    // End of variables declaration//GEN-END:variables
}
