/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankregister;

import java.awt.event.WindowEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Arrays;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.WindowConstants;

/**
 *
 * @author Eduardo Estrada
 */
public class TransActionForm extends javax.swing.JFrame {

    private BankAccount bankAccount;

    /**
     * Creates new form TransActionForm
     */
    public TransActionForm() {
        initComponents();
    }

    public void readFile() throws FileNotFoundException {

        File accountFile = new File("accountInfo.txt");
        Scanner fileScanner = new Scanner(accountFile);

        String accountline = "";
        String[] split_data = null;

        // loop thru the file
        while (fileScanner.hasNextLine()) {
            accountline = fileScanner.nextLine();
            split_data = accountline.split(",");

        }// end while
        // debug
        System.out.println(Arrays.toString(split_data));
        // CLOSE STREAM
        fileScanner.close();
        String accountOwner = split_data[0].trim();
        String accountType = split_data[1].trim();
        float accountBala = Float.parseFloat(split_data[2].trim());
        //int accountNum = Integer.parseInt(split_data[3].trim());

        bankAccount = new BankAccount(accountOwner, accountType, accountBala);

    }// end readFile

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        transTypeBtnGroup = new javax.swing.ButtonGroup();
        titleLbl = new javax.swing.JLabel();
        dateLbl = new javax.swing.JLabel();
        categoryLbl = new javax.swing.JLabel();
        amntLbl = new javax.swing.JLabel();
        dateTxtFld = new javax.swing.JTextField();
        catTxtFld = new javax.swing.JTextField();
        amtTxtFld = new javax.swing.JTextField();
        withDrwRdoBtn = new javax.swing.JRadioButton();
        depRdoBtn = new javax.swing.JRadioButton();
        addTransBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        titleLbl.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        titleLbl.setText("Account Transaction Form");

        dateLbl.setText("Date:");

        categoryLbl.setText("Category:");

        amntLbl.setText("Amount: $");

        dateTxtFld.setText(" ");
        dateTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateTxtFldActionPerformed(evt);
            }
        });

        catTxtFld.setText(" ");
        catTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catTxtFldActionPerformed(evt);
            }
        });

        amtTxtFld.setText(" ");

        transTypeBtnGroup.add(withDrwRdoBtn);
        withDrwRdoBtn.setText("Withdraw");
        withDrwRdoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withDrwRdoBtnActionPerformed(evt);
            }
        });

        transTypeBtnGroup.add(depRdoBtn);
        depRdoBtn.setText("Deposit");

        addTransBtn.setText("Add");
        addTransBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTransBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(withDrwRdoBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(depRdoBtn))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(amntLbl)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(dateLbl)
                                            .addGap(27, 27, 27)))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(catTxtFld)
                                        .addComponent(dateTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(amtTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(categoryLbl, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addTransBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelBtn)
                        .addGap(75, 75, 75))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(titleLbl)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(withDrwRdoBtn)
                    .addComponent(depRdoBtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoryLbl)
                    .addComponent(catTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amtTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amntLbl))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addTransBtn)
                    .addComponent(cancelBtn))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    

    
    
    private void dateTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateTxtFldActionPerformed

    private void catTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_catTxtFldActionPerformed

    private void withDrwRdoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withDrwRdoBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_withDrwRdoBtnActionPerformed

    private void addTransBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTransBtnActionPerformed
        try {
            // get the values from the fields
//            amtTxtFld
//            catTxtFld
//            dateTxtFld

            readFile();

            bankAccount.displayInfo();
            float depAmt = Float.parseFloat(amtTxtFld.getText());

            if (withDrwRdoBtn.isSelected()) {
                
                  if (bankAccount.withdraw(depAmt, dateTxtFld.getText(), catTxtFld.getText())) {
                    // clear fields
                    amtTxtFld.setText("");
                    catTxtFld.setText("");
                    dateTxtFld.setText("");
                } else {
                    // display an error
                    System.out.println("withdrawal error");
                }

                System.out.println("add button pressed - withdrawal radio button is selected");

            } else if (depRdoBtn.isSelected()) {

                if (bankAccount.deposit(depAmt, dateTxtFld.getText(), catTxtFld.getText())) {
                    // clear the fields
                    amtTxtFld.setText("");
                    catTxtFld.setText("");
                    dateTxtFld.setText("");
                } else {
                    // display an error
                    System.out.println("deposit error");
                }
                
                
                
                

            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(TransActionForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addTransBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        System.out.println("cancel button pressed");

    }//GEN-LAST:event_cancelBtnActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            bankAccount.recordTransActions();
        } catch (IOException ex) {
            Logger.getLogger(TransActionForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println("window closing");
    }//GEN-LAST:event_formWindowClosing

    /**
     *
     */
    public static void displayForm() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransActionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransActionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransActionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransActionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransActionForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addTransBtn;
    private javax.swing.JLabel amntLbl;
    private javax.swing.JTextField amtTxtFld;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JTextField catTxtFld;
    private javax.swing.JLabel categoryLbl;
    private javax.swing.JLabel dateLbl;
    private javax.swing.JTextField dateTxtFld;
    private javax.swing.JRadioButton depRdoBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel titleLbl;
    private javax.swing.ButtonGroup transTypeBtnGroup;
    private javax.swing.JRadioButton withDrwRdoBtn;
    // End of variables declaration//GEN-END:variables
}
