/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankregister;

//import java.awt.event.WindowEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.Date;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
//import javax.swing.WindowConstants;

/**
 *
 * @author Eduardo Estrada
 */
public class TransActionForm extends javax.swing.JFrame {

    private BankAccount bankAccount;

    /**
     * Creates new form TransActionForm
     */
    public TransActionForm() {
        initComponents();
        try {
            readFile();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(TransActionForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }// end constructor

    public void readFile() throws FileNotFoundException {

        File accountFile = new File("accountInfo.txt");
        Scanner fileScanner = new Scanner(accountFile);

        String accountline;
        String[] split_data = null;

        // loop thru the file
        while (fileScanner.hasNextLine()) {
            accountline = fileScanner.nextLine();
            split_data = accountline.split(",");

        }// end while
        // debug
        System.out.println(Arrays.toString(split_data));
        // CLOSE STREAM
        fileScanner.close();
        String accountOwner = split_data[0].trim();
        String accountType = split_data[1].trim();
        float accountBala = Float.parseFloat(split_data[2].trim());
        //int accountNum = Integer.parseInt(split_data[3].trim());

        bankAccount = new BankAccount(accountOwner, accountType, accountBala);
        balanceResultTxtFld.setText(Float.toString(bankAccount.getBalance()));
        acctNameValueLbl.setText(bankAccount.getActype());

    }// end readFile

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        transTypeBtnGroup = new javax.swing.ButtonGroup();
        titleLbl = new javax.swing.JLabel();
        dateLbl = new javax.swing.JLabel();
        categoryLbl = new javax.swing.JLabel();
        amntLbl = new javax.swing.JLabel();
        catTxtFld = new javax.swing.JTextField();
        amtTxtFld = new javax.swing.JTextField();
        withDrwRdoBtn = new javax.swing.JRadioButton();
        depRdoBtn = new javax.swing.JRadioButton();
        addTransBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        balanceLbl = new javax.swing.JLabel();
        balanceResultTxtFld = new javax.swing.JTextField();
        acctNameLbl = new javax.swing.JLabel();
        acctNameValueLbl = new javax.swing.JLabel();
        payeeLbl = new javax.swing.JLabel();
        payeeTxtFld = new javax.swing.JTextField();
        checkNumLbl = new javax.swing.JLabel();
        checkNumTxtFld = new javax.swing.JTextField();
        datePicker = new org.jdesktop.swingx.JXDatePicker();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        titleLbl.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        titleLbl.setText("Account Transaction Form");

        dateLbl.setText("Date:");

        categoryLbl.setText("Category:");

        amntLbl.setText("Amount: $");

        catTxtFld.setText(" ");

        amtTxtFld.setText(" ");

        transTypeBtnGroup.add(withDrwRdoBtn);
        withDrwRdoBtn.setText("Withdraw");

        transTypeBtnGroup.add(depRdoBtn);
        depRdoBtn.setText("Deposit");

        addTransBtn.setText("Enter");
        addTransBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTransBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        balanceLbl.setText("Balance: $");

        balanceResultTxtFld.setEditable(false);
        balanceResultTxtFld.setText(" ");

        acctNameLbl.setText("Account Name:");

        acctNameValueLbl.setText("acct name");

        payeeLbl.setText("Payee:");

        payeeTxtFld.setText(" ");
        payeeTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payeeTxtFldActionPerformed(evt);
            }
        });

        checkNumLbl.setText("Check #:");

        checkNumTxtFld.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addTransBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelBtn)
                .addGap(76, 76, 76))
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(withDrwRdoBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(depRdoBtn)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(amntLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(balanceLbl, javax.swing.GroupLayout.Alignment.TRAILING))
                                            .addComponent(categoryLbl)
                                            .addComponent(payeeLbl)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dateLbl)
                                            .addComponent(checkNumLbl))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(balanceResultTxtFld, javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(amtTxtFld, javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(catTxtFld, javax.swing.GroupLayout.Alignment.CENTER)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(payeeTxtFld, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                                            .addComponent(checkNumTxtFld, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                                            .addComponent(datePicker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(44, 44, 44))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(acctNameLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(acctNameValueLbl))
                            .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(titleLbl)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(withDrwRdoBtn)
                    .addComponent(depRdoBtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acctNameLbl)
                    .addComponent(acctNameValueLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateLbl)
                    .addComponent(datePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkNumTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkNumLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(payeeTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(payeeLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoryLbl)
                    .addComponent(catTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amtTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amntLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(balanceResultTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(balanceLbl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addTransBtn)
                    .addComponent(cancelBtn))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void addTransBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTransBtnActionPerformed
        
        String datePattern = "dd/MM/yyyy";
        DateFormat dateFormat = new SimpleDateFormat(datePattern);
        Date selectedDate = datePicker.getDate();
        String transDate = dateFormat.format(selectedDate);
        
        bankAccount.displayInfo();

        float depAmt = Float.parseFloat(amtTxtFld.getText());

        System.out.println(datePicker.getDate());

        

        if (withDrwRdoBtn.isSelected()) {

            if (bankAccount.withdraw(depAmt, transDate, catTxtFld.getText(), payeeTxtFld.getText(), checkNumTxtFld.getText())) {
                // clear fields
                amtTxtFld.setText("");
                catTxtFld.setText("");
                // dateTxtFld.setText("");
                payeeTxtFld.setText("");
                checkNumTxtFld.setText("");
                balanceResultTxtFld.setText(Float.toString(bankAccount.getBalance()));
            } else {
                // display an error
                System.out.println("withdrawal error");
            }

            System.out.println("add button pressed - withdrawal radio button is selected");

        } else if (depRdoBtn.isSelected()) {

            if (bankAccount.deposit(depAmt, transDate, catTxtFld.getText(), payeeTxtFld.getText(), checkNumTxtFld.getText())) {
                // clear the fields
                amtTxtFld.setText("");
                catTxtFld.setText("");
                // dateTxtFld.setText("");
                payeeTxtFld.setText("");
                checkNumTxtFld.setText("");
                balanceResultTxtFld.setText(Float.toString(bankAccount.getBalance()));
            } else {
                // display an error
                System.out.println("deposit error");
            } // end if successful deposit

        }// end if either radio button selected

    }//GEN-LAST:event_addTransBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // cancel button needs to close out this form
        System.out.println("cancel button pressed");

    }//GEN-LAST:event_cancelBtnActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            bankAccount.recordTransActions();
        } catch (IOException ex) {
            Logger.getLogger(TransActionForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println("window closing");
    }//GEN-LAST:event_formWindowClosing

    private void payeeTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payeeTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_payeeTxtFldActionPerformed

    /**
     *
     */
    public static void displayForm() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransActionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransActionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransActionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransActionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransActionForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel acctNameLbl;
    private javax.swing.JLabel acctNameValueLbl;
    private javax.swing.JButton addTransBtn;
    private javax.swing.JLabel amntLbl;
    private javax.swing.JTextField amtTxtFld;
    private javax.swing.JLabel balanceLbl;
    private javax.swing.JTextField balanceResultTxtFld;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JTextField catTxtFld;
    private javax.swing.JLabel categoryLbl;
    private javax.swing.JLabel checkNumLbl;
    private javax.swing.JTextField checkNumTxtFld;
    private javax.swing.JLabel dateLbl;
    private org.jdesktop.swingx.JXDatePicker datePicker;
    private javax.swing.JRadioButton depRdoBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel payeeLbl;
    private javax.swing.JTextField payeeTxtFld;
    private javax.swing.JLabel titleLbl;
    private javax.swing.ButtonGroup transTypeBtnGroup;
    private javax.swing.JRadioButton withDrwRdoBtn;
    // End of variables declaration//GEN-END:variables
}
